pipeline {
    agent any 
    
    tools {
        nodejs 'NodeJs 18'
    }

    stages {
        stage ('Build') {
            steps {
                echo 'Building the app...'
            }
        }

        stage ('Test') {
            steps {
                echo 'Running tests...'
            }
        }

        stage ('Deploy') {
            steps {
                echo 'Deploying the app...'
            }
        }
    }
}
