pipeline {
    agent any 
    
    environment {
        NODE_ENV = 'development'
    }

    tools {
        nodejs 'NodeJs 18'
    }

    stages {
        stage ('Checkout') {
            steps {
                git 'https://github.com/AliShahzadKhan/node-js-react-app.git'
            }
        }

        stage ('Install Dependencies') {
            steps {
                sh 'npm install --verbose'
            }
        }

        stage ('Build') {
            steps {
                echo 'Building the app...'
                sh 'npm test'
            }
        }

        stage ('Test') {
            steps {
                echo 'Running tests...'
            }
        }

        stage ('Deploy') {
            steps {
                echo 'Deploying the app...'
            }
        }
    }

    post {
        success {
            echo 'Build was successful!'
        }
        failure {
            echo 'Build failed!'
        }
    }
}
